#!/bin/bash
output_file="yuriBertozzi.txt"
clear
echo "**********************************************************************************************" >> "$output_file"
echo "***                                                                                        ***" >> "$output_file"
echo "***                          COMPUTER ARCHITECTURE AND TECHNOLOGY                          ***" >> "$output_file"
echo "***                                                                                        ***" >> "$output_file"
echo "**********************************************************************************************" >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                          Question 2.2                                        " >> "$output_file"
echo "                                                                                              " >> "$output_file"   
echo " Running list of command into a shell script and automate execution                           " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo " Student: Yuri Bertozzi                                                                       " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo " Date: April 2024                                                                             " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "**********************************************************************************************" >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  First command: date                                                                       *" >> "$output_file"
echo "*  date is used to display the system date and time.                                         *" >> "$output_file"
echo "*  date is: + $(date)                                                                         " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Second  command: hostname                                                                 *" >> "$output_file"
echo "*  hostname is used to obtain DNS and NIS.                                                   *" >> "$output_file"
echo "*  hostname is: + $(hostname)                                                                 " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Third command: arch                                                                       *" >> "$output_file"
echo "*  arch is displaying the architecture of the machine.                                       *" >> "$output_file"
echo "*  arch is: + $(arch)                                                                         " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Fourth command: uname -a                                                                  *" >> "$output_file"
echo "*  uname display informations about Linux machine, -a is all                                 *" >> "$output_file"
echo "*  uname -a is: + $(uname -a | fold -w 66 | sed 's/^/*  /')                                   " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Fifth command: uptime                                                                     *" >> "$output_file"
echo "*  uptime is showing how long the machine is running.                                        *" >> "$output_file"
echo "*  uptime is: + $(uptime | fold -w 66 | sed 's/^/*  /')                                       " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Sixth command: whoami                                                                     *" >> "$output_file"
echo "*  whoami shows the name of the current user                                                 *" >> "$output_file"
echo "*  whoami is: + $(whoami | fold -w 66 | sed 's/^/*  /')                                       " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Seventh command: who                                                                      *" >> "$output_file"
echo "*  who is showing username, terminal ID, login times, and IP address                         *" >> "$output_file"
echo "*  who is: + $(who | fold -w 66 | sed 's/^/*  /')                                             " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Eight command: w                                                                          *" >> "$output_file"
echo "*  w gives information about who is using the computer.                                      *" >> "$output_file"
echo "*  w is: + $(w | fold -w 66 | sed 's/^/*  /')                                                 " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Ninth command: top                                                                        *" >> "$output_file"
echo "*  top is showing list of process that are running.                                          *" >> "$output_file"
num_iterations=5
top_output=$(top -b -n $num_iterations | head -5)
echo "$top_output" | sed 's/^/*  /'                                                                   >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "*  Tenth command: history                                                                    *" >> "$output_file"
echo "*  history display the list of the command input in the shell.                               *" >> "$output_file"
echo "*  the last 15 command of history are:                                                        " >> "$output_file"
history_file="$HOME/.bash_history"
tail -n 15 "$history_file" | sed 's/^/*  /'                                                           >> "$output_file"
echo "                                                                                              " >> "$output_file"
echo "                                  **** end of script ****                                     " >> "$output_file"
echo "***                                                                                        ***" >> "$output_file"
echo "***                                  copyright Yuri :)                                     ***" >> "$output_file"
echo "***                                                                                        ***" >> "$output_file"
echo "**********************************************************************************************" >> "$output_file"
